description: >-
  Aussiemoneyman (AMM) was started simply by Nicholas sharing his extensive
  research with a goal to get the best by doing the least work. This started as
  a simple comparison of all Australian Peer-to-Peer investing platforms
  (something not done previously). Today AMM provides various real value
  providing content from investing in P2P to making money from Market Research.
email: aussiemoneymanblog@gmail.com
title: AussieMoneyMan
url: "https://gallant-shannon-412137.netlify.com"