serv:
  box_1_h1: Comparasions and reviews of financial products and services
  box_1_p: >-
    We review and compare various financial products and services so you can
    make the best decsions for you and your money.
  box_1_small_span: AMM Services
  box_2_h1: Speaking Events
  box_2_p: >-
    Should you wish to have Nicholas speak at an event whether it be on Finance,
    personal development or something more specfic, you can request such by
    clicking the button below.
  box_2_small_span: AMM Services
  box_3_h1: School Courses in partnership with BOP Industries
  box_3_p: >-
    BOP Industries and AMM have partnered up to make a life changing course.
    More to come soon!
  box_3_small_span: AMM Services
  box_4_h1: Recommendations for general money making
  box_4_p: >-
    One of AMM's main difference is that we don't just share ways to save and
    invest money but also make it! We share real, efficent and doable ways to
    make money that we use.
  box_4_small_span: AMM Services
  header_h1: Providing You Best Services
  header_p: Take a read below
  main_h1: Best Services Awaits You
  main_p: >-
    What can we offer you? Well quite a bit, have a scroll below and find how we
    may be of assistance. 
  sub_h1_1: Afiliate Marketing
  sub_h1_2: eCommerce
  sub_h1_3: Youtube
  sub_h1_4: Blogging
  sub_heading: 'On occasions, We Provide Mentorship in The Following'
  sub_p_1: 'We have built affiliate incomes to 10,000+ and know the tricks of the trade.'
  sub_p_2: >-
    Building, running, scaling and selling eCommerce business we have done it
    all.
  sub_p_3: 'Finding your niche, video tricks, playlists, editing, we know the guy.'
  sub_p_4: ' Today blogging is much more difficult than before, you will need to use new methods if you want to succeed and we know them all.'
